{
 "title": "Ceph - OSD",
 "description": "CEPH OSD Status (ceph-mgr, multi-cluster)",
 "tags": [
  "ceph",
  "osd"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "job",
    "label": "Cluster",
    "query": {
     "query": "label_values(ceph_mon_quorum_status, job)"
    }
   },
   {
    "name": "osd",
    "label": "OSD",
    "query": {
     "query": "label_values(ceph_osd_up{job=\"$job\"}, ceph_daemon)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "OSD Status / Total OSDs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_up{job=\"$job\",ceph_daemon=~\"$osd\"})"
    }
   ]
  },
  {
   "title": "Available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_in{job=\"$job\",ceph_daemon=~\"$osd\"})"
    }
   ]
  },
  {
   "title": "Total OSDs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_up{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Utilization OSD: $osd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PGs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceph_osd_numpg{job=\"$job\",ceph_daemon=~\"$osd\"}",
     "legendFormat": "{{ ceph_daemon }} - Number of PGs"
    },
    {
     "expr": "avg(ceph_osd_numpg{job=\"$job\"})",
     "legendFormat": "Average Number of PGs in the Cluster"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_stat_bytes_used{job=\"$job\",ceph_daemon=~\"$osd\"})/sum(ceph_osd_stat_bytes{job=\"$job\",ceph_daemon=~\"$osd\"})*100"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(ceph_osd_op_r{job=\"$job\",ceph_daemon=~\"$osd\"}[$interval])",
     "legendFormat": "{{ ceph_daemon }} - read"
    },
    {
     "expr": "rate(ceph_osd_op_w{job=\"$job\",ceph_daemon=~\"$osd\"}[$interval])",
     "legendFormat": "{{ ceph_daemon }} - write"
    },
    {
     "expr": "rate(ceph_osd_op_rw{job=\"$job\",ceph_daemon=~\"$osd\"}[$interval])",
     "legendFormat": "{{ ceph_daemon }} - overwrite"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_osd_op_r_out_bytes{job=\"$job\",ceph_daemon=~\"$osd\"}[$interval])",
     "legendFormat": "{{ ceph_daemon }} - read"
    },
    {
     "expr": "irate(ceph_osd_op_w_in_bytes{job=\"$job\",ceph_daemon=~\"$osd\"}[$interval])",
     "legendFormat": "{{ ceph_daemon }} - write"
    },
    {
     "expr": "irate(ceph_osd_op_rw_in_bytes{job=\"$job\",ceph_daemon=~\"$osd\"}[$interval])",
     "legendFormat": "{{ ceph_daemon }} - overwrite"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "1000*increase(ceph_osd_op_r_latency_sum{job=\"$job\",ceph_daemon=~\"$osd\"}[1m])/clamp_min(increase(ceph_osd_op_r_latency_count{job=\"$job\",ceph_daemon=~\"$osd\"}[1m]),1)",
     "legendFormat": "{{ ceph_daemon }} - read"
    },
    {
     "expr": "1000*increase(ceph_osd_op_w_latency_sum{job=\"$job\",ceph_daemon=~\"$osd\"}[1m])/clamp_min(increase(ceph_osd_op_w_latency_count{job=\"$job\",ceph_daemon=~\"$osd\"}[1m]),1)",
     "legendFormat": "{{ ceph_daemon }} - write"
    },
    {
     "expr": "1000*increase(ceph_osd_op_rw_latency_sum{job=\"$job\",ceph_daemon=~\"$osd\"}[1m])/clamp_min(increase(ceph_osd_op_rw_latency_count{job=\"$job\",ceph_daemon=~\"$osd\"}[1m]),1)",
     "legendFormat": "{{ ceph_daemon }} - overwrite"
    }
   ]
  },
  {
   "title": "OSD Apply Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "ceph_osd_apply_latency_ms{job=\"$job\",ceph_daemon=~\"$osd\"}",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "OSD Commit Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "ceph_osd_commit_latency_ms{job=\"$job\",ceph_daemon=~\"$osd\"}",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {}
   ]
  },
  {
   "title": "OSD Storage Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ceph_osd_stat_bytes_used{job=\"$job\",ceph_daemon=~\"$osd\"}",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "OSD Used %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ceph_osd_stat_bytes_used{job=\"$job\",ceph_daemon=~\"$osd\"}/ceph_osd_stat_bytes{job=\"$job\",ceph_daemon=~\"$osd\"}*100",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "OSD Storage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ceph_osd_stat_bytes{ceph_daemon=~\"$osd\"}-ceph_osd_stat_bytes_used{ceph_daemon=~\"$osd\"}",
     "legendFormat": "{{ ceph_daemon }} - Available "
    },
    {
     "expr": "ceph_osd_stat_bytes_used{ceph_daemon=~\"$osd\"}",
     "legendFormat": "{{ ceph_daemon }} - Used"
    }
   ]
  },
  {
   "title": "RocksDB STATE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {}
   ]
  },
  {
   "title": "BlueFS Log Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceph_bluefs_log_bytes{job=\"$job\",ceph_daemon=~\"$osd\"}",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "BlueFS Slow DB %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ceph_bluefs_slow_used_bytes{job=\"$job\",ceph_daemon=~\"$osd\"}/ceph_bluefs_slow_total_bytes{job=\"$job\",ceph_daemon=~\"$osd\"}*100",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  }
 ]
}