filebeatConfig:
  filebeat.yml: |
    filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        processors:
          - add_kubernetes_metadata:
              host: ${NODE_NAME}
              matchers:
                - logs_path:
                    logs_path: "/var/log/containers/"
          - add_fields:
              target: ""
              fields:
                cluster: "CLUSTER_NAME"

    output.logstash:
      hosts: ["logstash:5044"]
      ssl:
        enabled: false

    output.elasticsearch:
      host: '${NODE_NAME}'
      hosts: ["https://elasticsearch:9200"]
      username: "elastic"
      password: "your-password"

      ssl:
        enabled: false
        verification_mode: "none"

      index: "virtual-%{[fields.cluster]}-%{[@metadata][beat]}-%{+yyyy.MM.dd}"

    setup.template.name: "virtual"
    setup.template.pattern: "virtual-*"

extraEnvs:
  - name: NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
