version: '3.8'

services:
  nginx:
    image: 10.2.217.9:8082/nginx:alpine3.20
    container_name: nginx
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    restart: always
    volumes:
      - ./data/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/conf.d/:/etc/nginx/conf.d/
      - ./data/certs/:/certs
      - ./data/logs/:/var/log/nginx/